[project]
name= "src"
version='0.0.1'
description="An MLOPs project for productioning model"
authors = [{name="Krunal Bhammar" , email ="krunalahir0538@gmail.com"}]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}